Fix typings for children in custom components (#14)
Previously you'd get this error if your custom component had children:

```
code.tsx:96:8 - error TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & { children: FigmaDeclarativeNode | FigmaDeclarativeNode[]; }'.
  Property 'children' is missing in type '{}' but required in type '{ children: FigmaDeclarativeNode | FigmaDeclarativeNode[]; }'.

96       <CustomComponentWithChildren>
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  code.tsx:24:3
    24   children: FigmaDeclarativeNode | FigmaDeclarativeNode[]
         ~~~~~~~~
    'children' is declared here.
```